### ISSUE TITLE
Use OAuth2 for authentication

### ISSUE THREAD

**Issue by brianbs** [angusws/tcx2nikeplus#12]
https://developer.nike.com/sdk/ios-sdk/ios-authentication.html

I'd be happy to help :)

**Comment by brianbs** [comment]
Oops what I linked was the iOS sdk, JS is here https://developer.nike.com/sdk/web-starter-guide1/javascript-authorization.html. I haven't read through the API docs to be honest, but it just feels weird to have to login through your site rather than be authorized through nike+.

**Comment by sfdye** [comment]
@brianbs you should read the developer site more carefully. there is no point at the moment to do OAuth, because Nike+ will only work with trusted third-party. You can't just get an `client_id` and `client_secret` for free. As the author said, he got the value from sniffing https post request of the Nike+ iOS app. Right now it's the only way.

**Comment by brianbs** [comment]
Ah okay fair enough, I haven't read through the API docs at all.  Seems strange on Nikes part though, I'll go ahead and close this.  Thanks!
